# Generated by Django 2.1.5 on 2019-01-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('schedule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=10)),
                ('locphone', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('mgrphone1', models.CharField(max_length=200)),
                ('mgremail', models.CharField(max_length=200)),
                ('principal', models.CharField(max_length=200)),
                ('prncphone', models.CharField(max_length=200)),
                ('prncemail', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ircoapp.Site'),
        ),
    ]
